version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=fabianamoveis.postgres.database.azure.com
      - DB_PORT=5432
      - DB_USERNAME=fabianamoveis
      - DB_PASSWORD=pucMINAS123$
      - DB_NAME=fabianamoveis
      - DB_SSL=true
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M